import './global.css';
import { AuthProvider } from './context/AuthContext';

export const metadata = {
  title: 'Welcome to TaniConnect',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
